/**
 * DATI GIOCATORI — FANTACALCIO26
 * ==============================
 * Generato automaticamente da: listone-serie-a-2026-2027.pdf
 * Quotazioni aggiornate al 30/08/2026 · 564 calciatori
 *
 * ⚠️ REGOLA FONDAMENTALE:
 * Il campo `role` è preso SEMPRE dalla lista ufficiale (PDF).
 * Mai dai ruoli riportati in altre fonti. In caso di conflitto vince il PDF.
 *
 * `value`    = quotazione ufficiale (Q) dal PDF.
 * `age`      = età (dal PDF).
 * `maxSpend` = MASSIMO DI SPESA (colonna "Prezzo" di "Carmy Classic 26_27.xlsx").
 *              È il riferimento da cui attingere per l'offerta.
 * `altRole`  = ruolo SECONDO la valutazione xlsx, presente SOLO se diverso dal
 *              ruolo originale PDF (campo `role`). Il ruolo ufficiale resta `role`.
 * `titolarita` = titolarità (scala 0–5) dal file xlsx "Carmy Classic".
 *
 * I campi `called` / `inSquad` / `paidPrice` NON vanno scritti qui:
 * sono gestiti automaticamente dall'app via localStorage.
 */

const PLAYERS = [
  { id: "p001", name: "SVILAR", team: "ROM", role: "PORTIERI", value: 22, age: 27, titolarita: 5, maxSpend: 36, valCarmy: 33, valProfeta: 42, valTattico: 33, notes: "" },
  { id: "p002", name: "CARNESECCHI", team: "ATA", role: "PORTIERI", value: 20, age: 26, titolarita: 5, maxSpend: 26, valCarmy: 22, valProfeta: 36, valTattico: 21, notes: "" },
  { id: "p003", name: "MAIGNAN", team: "MIL", role: "PORTIERI", value: 20, age: 31, titolarita: 5, maxSpend: 27, valCarmy: 28, valProfeta: 30, valTattico: 24, notes: "" },
  { id: "p004", name: "MARTINEZ JO", team: "INT", role: "PORTIERI", value: 20, age: 28, titolarita: 3, maxSpend: 28, valCarmy: 26, valProfeta: 33, valTattico: 24, notes: "" },
  { id: "p005", name: "BUTEZ", team: "COM", role: "PORTIERI", value: 19, age: 31, titolarita: 5, maxSpend: 27, valCarmy: 26, valProfeta: 30, valTattico: 24, notes: "" },
  { id: "p006", name: "VICARIO", team: "JUV", role: "PORTIERI", value: 19, age: 30, titolarita: 5, maxSpend: 30, valCarmy: 27, valProfeta: 36, valTattico: 27, notes: "" },
  { id: "p007", name: "MERET", team: "NAP", role: "PORTIERI", value: 16, age: 29, titolarita: 3, maxSpend: 27, valCarmy: 25, valProfeta: 33, valTattico: 24, notes: "" },
  { id: "p008", name: "DE GEA", team: "FIO", role: "PORTIERI", value: 14, age: 36, titolarita: 5, maxSpend: 18, valCarmy: 14, valProfeta: 18, valTattico: 21, notes: "" },
  { id: "p009", name: "SKORUPSKI", team: "BOL", role: "PORTIERI", value: 14, age: 35, titolarita: 4, maxSpend: 9, valCarmy: 10, valProfeta: 12, valTattico: 6, notes: "" },
  { id: "p010", name: "CAPRILE", team: "CAG", role: "PORTIERI", value: 13, age: 25, titolarita: 5, maxSpend: 5, valCarmy: 6, valProfeta: 6, valTattico: 4, notes: "" },
  { id: "p011", name: "FALCONE", team: "LEC", role: "PORTIERI", value: 13, age: 31, titolarita: 5, maxSpend: 7, valCarmy: 8, valProfeta: 10, valTattico: 3, notes: "" },
  { id: "p012", name: "OKOYE", team: "UDI", role: "PORTIERI", value: 12, age: 27, titolarita: 5, maxSpend: 8, valCarmy: 7, valProfeta: 10, valTattico: 6, notes: "" },
  { id: "p013", name: "BIJLOW", team: "GEN", role: "PORTIERI", value: 11, age: 28, titolarita: 4, maxSpend: 6, valCarmy: 5, valProfeta: 6, valTattico: 6, notes: "" },
  { id: "p014", name: "MANDAS", team: "LAZ", role: "PORTIERI", value: 11, age: 25, titolarita: 4, maxSpend: 12, valCarmy: 13, valProfeta: 12, valTattico: 12, notes: "" },
  { id: "p015", name: "MURIC", team: "SAS", role: "PORTIERI", value: 9, age: 28, titolarita: 4, maxSpend: 3, valCarmy: 3, valProfeta: 3, valTattico: 4, notes: "" },
  { id: "p016", name: "STANKOVIC", team: "VEN", role: "PORTIERI", value: 9, age: 24, titolarita: 4, maxSpend: 3, valCarmy: 3, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p017", name: "MILINKOVIC", team: "NAP", role: "PORTIERI", value: 7, age: 29, titolarita: 3, maxSpend: 6, valCarmy: 7, valProfeta: 3, valTattico: 9, notes: "" },
  { id: "p018", name: "PALMISANI", team: "FRO", role: "PORTIERI", value: 7, age: 22, titolarita: 4, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p019", name: "THIAM", team: "MON", role: "PORTIERI", value: 7, age: 28, titolarita: 4, maxSpend: 2, valCarmy: 2, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p020", name: "MOTTA", team: "LAZ", role: "PORTIERI", value: 5, age: 21, titolarita: 2, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p021", name: "PALEARI", team: "TOR", role: "PORTIERI", value: 5, age: 34, titolarita: 2, maxSpend: 3, valCarmy: 1, valProfeta: 1, valTattico: 6, notes: "" },
  { id: "p022", name: "DAFFARA", team: "PAR", role: "PORTIERI", value: 4, age: 22, titolarita: 2, maxSpend: 1, valCarmy: 0, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p023", name: "DESPLANCHES", team: "FRO", role: "PORTIERI", value: 3, age: 23, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p024", name: "PROVEDEL", team: "INT", role: "PORTIERI", value: 3, age: 32, titolarita: 3, maxSpend: 7, valCarmy: 8, valProfeta: 6, valTattico: 6, notes: "" },
  { id: "p025", name: "CORVI", team: "PAR", role: "PORTIERI", value: 2, age: 25, titolarita: 4, maxSpend: 3, valCarmy: 2, valProfeta: 1, valTattico: 6, notes: "" },
  { id: "p026", name: "MONTIPO'", team: "VEN", role: "PORTIERI", value: 2, age: 30, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p027", name: "TERRACCIANO", team: "MIL", role: "PORTIERI", value: 2, age: 36, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p028", name: "AUDERO", team: "COM", role: "PORTIERI", value: 1, age: 29, notes: "" },
  { id: "p029", name: "BORBEI", team: "LEC", role: "PORTIERI", value: 1, age: 23, notes: "" },
  { id: "p030", name: "CHRISTENSEN", team: "FIO", role: "PORTIERI", value: 1, age: 27, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p031", name: "CONTINI", team: "NAP", role: "PORTIERI", value: 1, age: 30, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p032", name: "DE MARZI GIORGIO", team: "ROM", role: "PORTIERI", value: 1, age: 19, maxSpend: 0, notes: "" },
  { id: "p033", name: "DI GENNARO", team: "INT", role: "PORTIERI", value: 1, age: 33, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p034", name: "FURLANETTO", team: "LAZ", role: "PORTIERI", value: 1, age: 24, notes: "" },
  { id: "p035", name: "GOLLINI", team: "ROM", role: "PORTIERI", value: 1, age: 31, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p036", name: "GRABARA", team: "JUV", role: "PORTIERI", value: 1, age: 27, titolarita: 2, maxSpend: 2, valCarmy: 2, valProfeta: 3, valTattico: 1, notes: "" },
  { id: "p037", name: "GRANDI", team: "VEN", role: "PORTIERI", value: 1, age: 34, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p038", name: "HAPPONEN", team: "BOL", role: "PORTIERI", value: 1, age: 19, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p039", name: "ISRAEL", team: "TOR", role: "PORTIERI", value: 1, age: 26, notes: "" },
  { id: "p040", name: "LEZZERINI", team: "FIO", role: "PORTIERI", value: 1, age: 31, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p041", name: "LOLIC", team: "FRO", role: "PORTIERI", value: 1, age: 22, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p043", name: "MASCARDI", team: "TOR", role: "PORTIERI", value: 1, age: 20, titolarita: 4, maxSpend: 3, valCarmy: 1, valProfeta: 6, valTattico: 1, notes: "" },
  { id: "p044", name: "PADELLI", team: "UDI", role: "PORTIERI", value: 1, age: 41, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p045", name: "PENEV", team: "LEC", role: "PORTIERI", value: 1, age: 18, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p565", name: "BLEVE", team: "LEC", role: "PORTIERI", value: 1, age: 31, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p046", name: "PESSINA", team: "BOL", role: "PORTIERI", value: 1, age: 19, maxSpend: 0, notes: "" },
  { id: "p047", name: "PIANA", team: "UDI", role: "PORTIERI", value: 1, age: 23, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p048", name: "PINSOGLIO", team: "JUV", role: "PORTIERI", value: 1, age: 36, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p049", name: "PISSERI", team: "FRO", role: "PORTIERI", value: 1, age: 35, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p050", name: "POZZI", team: "VEN", role: "PORTIERI", value: 1, age: 26, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p051", name: "RADUNOVIC", team: "CAG", role: "PORTIERI", value: 1, age: 30, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p052", name: "RENZETTI", team: "LAZ", role: "PORTIERI", value: 1, age: 20, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p053", name: "ROSSI", team: "ATA", role: "PORTIERI", value: 1, age: 35, notes: "" },
  { id: "p054", name: "RUSSO", team: "SAS", role: "PORTIERI", value: 1, age: 25, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p055", name: "SATALINO", team: "SAS", role: "PORTIERI", value: 1, age: 27, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p056", name: "SHERRI", team: "CAG", role: "PORTIERI", value: 1, age: 29, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p057", name: "SIVIERO", team: "TOR", role: "PORTIERI", value: 1, age: 20, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p058", name: "SOMMARIVA", team: "GEN", role: "PORTIERI", value: 1, age: 29, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p059", name: "SPORTIELLO", team: "ATA", role: "PORTIERI", value: 1, age: 34, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p060", name: "STOLZ", team: "GEN", role: "PORTIERI", value: 1, age: 25, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p061", name: "STRAJNAR", team: "MON", role: "PORTIERI", value: 1, age: 19, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p062", name: "TORNQVIST", team: "COM", role: "PORTIERI", value: 1, age: 24, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p063", name: "TORRIANI", team: "MIL", role: "PORTIERI", value: 1, age: 21, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p064", name: "TURATI", team: "SAS", role: "PORTIERI", value: 1, age: 25, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p065", name: "VASQUEZ", team: "ROM", role: "PORTIERI", value: 1, age: 28, notes: "" },
  { id: "p066", name: "VIGORITO", team: "COM", role: "PORTIERI", value: 1, age: 36, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p067", name: "VISMARA", team: "ATA", role: "PORTIERI", value: 1, age: 23, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p068", name: "ASTALDI", team: "PAR", role: "PORTIERI", value: 0, age: 20, notes: "" },
  { id: "p069", name: "BREMER", team: "JUV", role: "DIFENSORI", value: 24, age: 29, titolarita: 5, maxSpend: 18, valCarmy: 18, valProfeta: 23, valTattico: 12, notes: "" },
  { id: "p070", name: "AKANJI", team: "INT", role: "DIFENSORI", value: 21, age: 31, titolarita: 4, maxSpend: 17, valCarmy: 16, valProfeta: 23, valTattico: 12, notes: "" },
  { id: "p071", name: "BASTONI", team: "INT", role: "DIFENSORI", value: 21, age: 27, titolarita: 5, maxSpend: 19, valCarmy: 15, valProfeta: 20, valTattico: 21, notes: "" },
  { id: "p072", name: "BISSECK", team: "INT", role: "DIFENSORI", value: 20, age: 26, titolarita: 3, maxSpend: 12, valCarmy: 13, valProfeta: 16, valTattico: 6, notes: "" },
  { id: "p073", name: "MANCINI", team: "ROM", role: "DIFENSORI", value: 20, age: 30, titolarita: 5, maxSpend: 17, valCarmy: 17, valProfeta: 23, valTattico: 12, notes: "" },
  { id: "p074", name: "PAVLOVIC", team: "MIL", role: "DIFENSORI", value: 20, age: 25, titolarita: 5, maxSpend: 14, valCarmy: 12, valProfeta: 18, valTattico: 12, notes: "" },
  { id: "p075", name: "DI LORENZO", team: "NAP", role: "DIFENSORI", value: 19, age: 33, titolarita: 5, maxSpend: 14, valCarmy: 13, valProfeta: 15, valTattico: 15, notes: "" },
  { id: "p076", name: "RRAHMANI", team: "NAP", role: "DIFENSORI", value: 19, age: 32, titolarita: 5, maxSpend: 17, valCarmy: 17, valProfeta: 23, valTattico: 12, notes: "" },
  { id: "p077", name: "KALULU", team: "JUV", role: "DIFENSORI", value: 18, age: 26, titolarita: 5, maxSpend: 14, valCarmy: 13, valProfeta: 20, valTattico: 9, notes: "" },
  { id: "p078", name: "NDICKA", team: "ROM", role: "DIFENSORI", value: 18, age: 27, titolarita: 5, maxSpend: 10, valCarmy: 11, valProfeta: 9, valTattico: 9, notes: "" },
  { id: "p079", name: "SOLET", team: "UDI", role: "DIFENSORI", value: 18, age: 26, titolarita: 5, maxSpend: 15, valCarmy: 16, valProfeta: 15, valTattico: 14, notes: "" },
  { id: "p080", name: "STONES", team: "INT", role: "DIFENSORI", value: 17, age: 32, titolarita: 3, maxSpend: 7, valCarmy: 4, valProfeta: 9, valTattico: 8, notes: "" },
  { id: "p081", name: "SCALVINI", team: "ATA", role: "DIFENSORI", value: 16, age: 23, titolarita: 5, maxSpend: 6, valCarmy: 9, valProfeta: 6, valTattico: 3, notes: "" },
  { id: "p082", name: "GILA", team: "MIL", role: "DIFENSORI", value: 15, age: 26, titolarita: 5, maxSpend: 8, valCarmy: 7, valProfeta: 9, valTattico: 9, notes: "" },
  { id: "p083", name: "OSTIGARD", team: "GEN", role: "DIFENSORI", value: 15, age: 27, titolarita: 5, maxSpend: 14, valCarmy: 10, valProfeta: 18, valTattico: 15, notes: "" },
  { id: "p084", name: "RAMON", team: "COM", role: "DIFENSORI", value: 15, age: 21, titolarita: 4, maxSpend: 13, valCarmy: 11, valProfeta: 17, valTattico: 11, notes: "" },
  { id: "p085", name: "CHALOBAH", team: "COM", role: "DIFENSORI", value: 13, age: 27, titolarita: 4, maxSpend: 14, valCarmy: 11, valProfeta: 18, valTattico: 12, notes: "" },
  { id: "p086", name: "HERMOSO", team: "ROM", role: "DIFENSORI", value: 13, age: 31, titolarita: 3, maxSpend: 5, valCarmy: 4, valProfeta: 8, valTattico: 3, notes: "" },
  { id: "p087", name: "HIEN", team: "ATA", role: "DIFENSORI", value: 13, age: 27, titolarita: 2, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p088", name: "TIAGO GABRIEL", team: "LEC", role: "DIFENSORI", value: 13, age: 22, titolarita: 5, maxSpend: 5, valCarmy: 1, valProfeta: 7, valTattico: 6, notes: "" },
  { id: "p089", name: "VASQUEZ", team: "GEN", role: "DIFENSORI", value: 13, age: 28, titolarita: 5, maxSpend: 6, valCarmy: 7, valProfeta: 8, valTattico: 3, notes: "" },
  { id: "p090", name: "BARTESAGHI", team: "MIL", role: "DIFENSORI", value: 12, age: 21, titolarita: 3, maxSpend: 5, valCarmy: 7, valProfeta: 3, valTattico: 6, notes: "" },
  { id: "p091", name: "BUONGIORNO", team: "NAP", role: "DIFENSORI", value: 12, age: 27, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p092", name: "DOEKHI", team: "LAZ", role: "DIFENSORI", value: 12, age: 28, titolarita: 3, maxSpend: 4, valCarmy: 2, valProfeta: 3, valTattico: 6, notes: "" },
  { id: "p093", name: "GABBIA", team: "MIL", role: "DIFENSORI", value: 12, age: 27, titolarita: 5, maxSpend: 3, valCarmy: 4, valProfeta: 1, valTattico: 5, notes: "" },
  { id: "p094", name: "JIMENEZ", team: "FIO", role: "DIFENSORI", value: 12, age: 21, titolarita: 3, maxSpend: 11, valCarmy: 9, valProfeta: 9, valTattico: 15, notes: "" },
  { id: "p095", name: "KEMPF", team: "COM", role: "DIFENSORI", value: 12, age: 31, titolarita: 3, maxSpend: 5, valCarmy: 4, valProfeta: 6, valTattico: 6, notes: "" },
  { id: "p096", name: "MIRANDA", team: "BOL", role: "DIFENSORI", value: 12, age: 26, titolarita: 5, maxSpend: 6, valCarmy: 7, valProfeta: 6, valTattico: 6, notes: "" },
  { id: "p097", name: "VALERI", team: "PAR", role: "DIFENSORI", value: 12, age: 28, titolarita: 5, maxSpend: 7, valCarmy: 8, valProfeta: 6, valTattico: 6, notes: "" },
  { id: "p098", name: "DRAGUSIN", team: "FIO", role: "DIFENSORI", value: 11, age: 24, titolarita: 4, maxSpend: 5, valCarmy: 4, valProfeta: 4, valTattico: 6, notes: "" },
  { id: "p099", name: "LUCUMI", team: "JUV", role: "DIFENSORI", value: 11, age: 28, titolarita: 3, maxSpend: 4, valCarmy: 2, valProfeta: 7, valTattico: 3, notes: "" },
  { id: "p100", name: "MINA", team: "CAG", role: "DIFENSORI", value: 11, age: 32, titolarita: 5, maxSpend: 3, valCarmy: 2, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p101", name: "VALLE", team: "COM", role: "DIFENSORI", value: 11, age: 22, titolarita: 3, maxSpend: 3, valCarmy: 4, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p102", name: "BADIASHILE MUKIN.", team: "NAP", role: "DIFENSORI", value: 10, age: 25, maxSpend: 4, notes: "" },
  { id: "p103", name: "CELIK", team: "JUV", role: "DIFENSORI", value: 10, age: 29, titolarita: 3, maxSpend: 6, valCarmy: 6, valProfeta: 8, valTattico: 3, notes: "" },
  { id: "p104", name: "COCO", team: "TOR", role: "DIFENSORI", value: 10, age: 27, titolarita: 5, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p105", name: "COUTO", team: "COM", role: "DIFENSORI", value: 10, age: 24, titolarita: 4, maxSpend: 9, valCarmy: 7, valProfeta: 12, valTattico: 9, notes: "" },
  { id: "p106", name: "DEL PRATO", team: "PAR", role: "DIFENSORI", value: 10, age: 27, maxSpend: 3, notes: "" },
  { id: "p107", name: "KOULIERAKIS", team: "ROM", role: "DIFENSORI", value: 10, age: 23, titolarita: 3, maxSpend: 7, valCarmy: 4, valProfeta: 9, valTattico: 8, notes: "" },
  { id: "p108", name: "MARUSIC", team: "LAZ", role: "DIFENSORI", value: 10, age: 34, titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p109", name: "ROMAGNOLI", team: "LAZ", role: "DIFENSORI", value: 10, age: 31, titolarita: 2, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p110", name: "TOMORI", team: "MIL", role: "DIFENSORI", value: 10, age: 29, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p111", name: "VALDEPENAS", team: "FIO", role: "DIFENSORI", value: 10, age: 20, titolarita: 3, maxSpend: 7, valCarmy: 4, valProfeta: 12, valTattico: 6, notes: "" },
  { id: "p112", name: "VOJVODA", team: "UDI", role: "DIFENSORI", value: 10, age: 31, titolarita: 4, maxSpend: 7, valCarmy: 7, valProfeta: 7, valTattico: 6, notes: "" },
  { id: "p113", name: "BEUKEMA", team: "NAP", role: "DIFENSORI", value: 9, age: 28, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p114", name: "COMUZZO", team: "TOR", role: "DIFENSORI", value: 9, age: 21, titolarita: 4, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p115", name: "GALLO", team: "LEC", role: "DIFENSORI", value: 9, age: 26, titolarita: 5, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p116", name: "HEGGEM", team: "BOL", role: "DIFENSORI", value: 9, age: 27, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p117", name: "HOLM", team: "BOL", role: "DIFENSORI", value: 9, age: 26, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p566", name: "THEATE", team: "BOL", role: "DIFENSORI", value: 10, age: 26, titolarita: 5, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p118", name: "IDZES", team: "SAS", role: "DIFENSORI", value: 9, age: 26, titolarita: 4, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p119", name: "ISMAJLI", team: "TOR", role: "DIFENSORI", value: 9, age: 30, titolarita: 4, maxSpend: 3, valCarmy: 2, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p120", name: "MARCANDALLI", team: "GEN", role: "DIFENSORI", value: 9, age: 24, titolarita: 5, maxSpend: 4, valCarmy: 4, valProfeta: 5, valTattico: 3, notes: "" },
  { id: "p121", name: "NUNO TAVARES", team: "LAZ", role: "DIFENSORI", value: 9, age: 26, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p122", name: "OBRADOR", team: "SAS", role: "DIFENSORI", value: 9, age: 22, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 2, valTattico: 2, notes: "" },
  { id: "p123", name: "PAVARD", team: "INT", role: "DIFENSORI", value: 9, age: 30, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p124", name: "PEDRAZA", team: "LAZ", role: "DIFENSORI", value: 9, age: 30, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p125", name: "RENSCH", team: "ROM", role: "DIFENSORI", value: 9, age: 23, titolarita: 3, maxSpend: 2, valCarmy: 2, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p126", name: "ŠUTALO", team: "LAZ", role: "DIFENSORI", value: 9, age: 26, titolarita: 4, maxSpend: 2, valCarmy: 1, valProfeta: 5, valTattico: 1, notes: "" },
  { id: "p127", name: "BELLA-KOTCHAP", team: "VEN", role: "DIFENSORI", value: 8, age: 25, titolarita: 5, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p128", name: "CORREIA", team: "VEN", role: "DIFENSORI", value: 8, age: 27, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p129", name: "GASPAR", team: "LEC", role: "DIFENSORI", value: 8, age: 29, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 1, notes: "" },
  { id: "p130", name: "KABASELE", team: "UDI", role: "DIFENSORI", value: 8, age: 35, titolarita: 4, maxSpend: 3, valCarmy: 2, valProfeta: 1, valTattico: 6, notes: "" },
  { id: "p131", name: "KELLY", team: "JUV", role: "DIFENSORI", value: 8, age: 28, titolarita: 3, maxSpend: 4, valCarmy: 4, valProfeta: 3, valTattico: 6, notes: "" },
  { id: "p132", name: "LEYSEN", team: "SAS", role: "DIFENSORI", value: 8, age: 23, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p133", name: "OBERT", team: "CAG", role: "DIFENSORI", value: 8, age: 24, titolarita: 5, maxSpend: 2, valCarmy: 2, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p134", name: "VEIGA", team: "LEC", role: "DIFENSORI", value: 8, age: 24, titolarita: 5, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p135", name: "VIERY", team: "FIO", role: "DIFENSORI", value: 8, age: 21, titolarita: 2, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p136", name: "WALUKIEWICZ", team: "SAS", role: "DIFENSORI", value: 8, age: 26, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p137", name: "BRACAGLIA", team: "FRO", role: "DIFENSORI", value: 7, age: 23, titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p138", name: "DE WINTER", team: "MIL", role: "DIFENSORI", value: 7, age: 24, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p139", name: "DOIG", team: "SAS", role: "DIFENSORI", value: 7, age: 24, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p140", name: "GHILARDI", team: "ROM", role: "DIFENSORI", value: 7, age: 23, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p141", name: "KAIKI", team: "COM", role: "DIFENSORI", value: 7, age: 23, titolarita: 3, maxSpend: 4, valCarmy: 2, valProfeta: 5, valTattico: 5, notes: "" },
  { id: "p142", name: "KOSSOUNOU", team: "ATA", role: "DIFENSORI", value: 7, age: 25, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p143", name: "MONTERISI", team: "FRO", role: "DIFENSORI", value: 7, age: 25, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p144", name: "ODENTHAL", team: "SAS", role: "DIFENSORI", value: 7, age: 26, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p145", name: "PONGRACIC", team: "FIO", role: "DIFENSORI", value: 7, age: 29, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p146", name: "RANIERI", team: "FIO", role: "DIFENSORI", value: 7, age: 27, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p147", name: "SIEBERT", team: "LEC", role: "DIFENSORI", value: 7, age: 24, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p148", name: "SMOLCIC", team: "COM", role: "DIFENSORI", value: 7, age: 26, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p149", name: "VALENTI", team: "PAR", role: "DIFENSORI", value: 7, age: 27, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p150", name: "VITIK", team: "BOL", role: "DIFENSORI", value: 7, age: 23, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 2, valTattico: 0, notes: "" },
  { id: "p151", name: "ZE PEDRO", team: "CAG", role: "DIFENSORI", value: 7, age: 29, titolarita: 4, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p152", name: "BERTOLA", team: "UDI", role: "DIFENSORI", value: 6, age: 23, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p153", name: "BRITSCHGI", team: "PAR", role: "DIFENSORI", value: 6, age: 20, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p154", name: "CARBONI", team: "MON", role: "DIFENSORI", value: 6, age: 25, titolarita: 4, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p155", name: "COMERT", team: "TOR", role: "DIFENSORI", value: 6, age: 28, titolarita: 3, maxSpend: 1, valCarmy: 0, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p156", name: "DELLI CARRI", team: "MON", role: "DIFENSORI", value: 6, age: 27, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p157", name: "GATTI", team: "JUV", role: "DIFENSORI", value: 6, age: 28, titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p158", name: "HALHAL", team: "VEN", role: "DIFENSORI", value: 6, age: 23, titolarita: 3, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p159", name: "KOFLER", team: "CAG", role: "DIFENSORI", value: 6, age: 21, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p160", name: "KOLASINAC", team: "ATA", role: "DIFENSORI", value: 6, age: 33, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p161", name: "MORENO", team: "VEN", role: "DIFENSORI", value: 6, age: 23, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p162", name: "PROVSTGAARD", team: "LAZ", role: "DIFENSORI", value: 6, age: 23, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 4, valTattico: 0, notes: "" },
  { id: "p163", name: "RODRIGUEZ", team: "CAG", role: "DIFENSORI", value: 6, age: 21, titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p164", name: "TCHATO MBIAYI", team: "FRO", role: "DIFENSORI", value: 6, age: 24, maxSpend: 0, notes: "" },
  { id: "p165", name: "CALVANI", team: "FRO", role: "DIFENSORI", value: 5, age: 22, titolarita: 4, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p166", name: "CANDE", team: "SAS", role: "DIFENSORI", value: 5, age: 28, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p167", name: "DOSSENA", team: "COM", role: "DIFENSORI", value: 5, age: 28, notes: "" },
  { id: "p168", name: "ESTUPINAN", team: "MIL", role: "DIFENSORI", value: 5, age: 28, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p169", name: "HAINAUT", team: "VEN", role: "DIFENSORI", value: 5, age: 24, titolarita: 3, maxSpend: 2, valCarmy: 4, valProfeta: 3, valTattico: 0, notes: "" },
  { id: "p170", name: "KAMBWALA", team: "COM", role: "DIFENSORI", value: 5, age: 22, titolarita: 2, maxSpend: 1, valCarmy: 0, valProfeta: 2, valTattico: 0, notes: "" },
  { id: "p171", name: "LAZZARI", team: "LAZ", role: "DIFENSORI", value: 5, age: 33, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p172", name: "LUCCHESI", team: "MON", role: "DIFENSORI", value: 5, age: 23, titolarita: 3, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p173", name: "MITAJ", team: "GEN", role: "DIFENSORI", value: 5, age: 23, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p174", name: "PELLEGRINI", team: "LAZ", role: "DIFENSORI", value: 5, age: 27, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p175", name: "SCHINGTIENNE", team: "VEN", role: "DIFENSORI", value: 5, age: 24, titolarita: 5, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p176", name: "TROILO", team: "PAR", role: "DIFENSORI", value: 5, age: 23, titolarita: 4, maxSpend: 2, valCarmy: 1, valProfeta: 2, valTattico: 3, notes: "" },
  { id: "p177", name: "ALHASSANE", team: "BOL", role: "DIFENSORI", value: 4, age: 24, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p178", name: "BALOGH", team: "PAR", role: "DIFENSORI", value: 4, age: 24, notes: "" },
  { id: "p179", name: "CASALE", team: "BOL", role: "DIFENSORI", value: 4, age: 28, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p180", name: "CITTADINI", team: "FRO", role: "DIFENSORI", value: 4, age: 24, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p181", name: "EBOSSE", team: "UDI", role: "DIFENSORI", value: 4, age: 27, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p182", name: "GOGLICHIDZE", team: "UDI", role: "DIFENSORI", value: 4, age: 22, notes: "" },
  { id: "p183", name: "HELLAND", team: "BOL", role: "DIFENSORI", value: 4, age: 21, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p184", name: "MARIANUCCI", team: "NAP", role: "DIFENSORI", value: 4, age: 22, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p185", name: "MARIN", team: "NAP", role: "DIFENSORI", value: 4, age: 24, titolarita: 4, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p186", name: "NDIAYE", team: "PAR", role: "DIFENSORI", value: 4, age: 24, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p187", name: "OYONO", team: "FRO", role: "DIFENSORI", value: 4, age: 25, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p188", name: "PALMA", team: "UDI", role: "DIFENSORI", value: 4, age: 18, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p189", name: "PATRIC", team: "LAZ", role: "DIFENSORI", value: 4, age: 33, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p190", name: "PUCZKA", team: "GEN", role: "DIFENSORI", value: 4, age: 21, titolarita: 2, maxSpend: 1, valCarmy: 0, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p191", name: "SVERKO", team: "VEN", role: "DIFENSORI", value: 4, age: 28, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p192", name: "TERZIC", team: "FRO", role: "DIFENSORI", value: 4, age: 27, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p193", name: "VAN DER BREMPT", team: "SAS", role: "DIFENSORI", value: 4, age: 24, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p194", name: "AKPOGUMA", team: "FRO", role: "DIFENSORI", value: 3, age: 31, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p195", name: "DIAWARA", team: "MIL", role: "DIFENSORI", value: 3, age: 20, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p196", name: "FRANJIć", team: "VEN", role: "DIFENSORI", value: 3, age: 26, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p197", name: "GIGOT", team: "LAZ", role: "DIFENSORI", value: 3, age: 33, notes: "" },
  { id: "p198", name: "GOLDANIGA", team: "COM", role: "DIFENSORI", value: 3, age: 33, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p199", name: "JEAN", team: "LEC", role: "DIFENSORI", value: 3, age: 26, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p200", name: "KOUADIO", team: "MON", role: "DIFENSORI", value: 3, age: 20, titolarita: 5, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p201", name: "OTOA", team: "GEN", role: "DIFENSORI", value: 3, age: 22, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p202", name: "AMORAN", team: "PAR", role: "DIFENSORI", value: 2, age: 22, notes: "" },
  { id: "p203", name: "ANTOV", team: "MON", role: "DIFENSORI", value: 2, age: 26, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p204", name: "CARBONI", team: "PAR", role: "DIFENSORI", value: 2, age: 23, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p567", name: "DROBNIC", team: "PAR", role: "DIFENSORI", value: 2, age: 19, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p205", name: "DE SILVESTRI", team: "BOL", role: "DIFENSORI", value: 2, age: 38, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p206", name: "KOUASSI", team: "LEC", role: "DIFENSORI", value: 2, age: 23, notes: "" },
  { id: "p207", name: "MAYE", team: "MON", role: "DIFENSORI", value: 2, age: 20, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p208", name: "MISSORI", team: "SAS", role: "DIFENSORI", value: 2, age: 22, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p209", name: "MLACIC", team: "UDI", role: "DIFENSORI", value: 2, age: 19, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p210", name: "NDABA", team: "LEC", role: "DIFENSORI", value: 2, age: 27, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p211", name: "PIERAGNOLO", team: "SAS", role: "DIFENSORI", value: 2, age: 23, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p212", name: "RUGANI", team: "JUV", role: "DIFENSORI", value: 2, age: 32, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p213", name: "ABANKWAH", team: "UDI", role: "DIFENSORI", value: 1, age: 22, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p214", name: "ADDO", team: "LEC", role: "DIFENSORI", value: 1, age: 21, notes: "" },
  { id: "p215", name: "AMEY", team: "FRO", role: "DIFENSORI", value: 1, age: 21, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p216", name: "CINQUEGRANO", team: "SAS", role: "DIFENSORI", value: 1, age: 22, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p217", name: "FAYED", team: "FRO", role: "DIFENSORI", value: 1, age: 23, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p218", name: "GOMES", team: "VEN", role: "DIFENSORI", value: 1, age: 18, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p220", name: "LIGUE", team: "VEN", role: "DIFENSORI", value: 1, age: 21, notes: "" },
  { id: "p221", name: "MACCHIONI", team: "SAS", role: "DIFENSORI", value: 1, age: 20, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p222", name: "PAZ", team: "SAS", role: "DIFENSORI", value: 1, age: 24, notes: "" },
  { id: "p223", name: "ZIOLKOWSKI", team: "MON", role: "DIFENSORI", value: 1, age: 21, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p224", name: "CALHANOGLU", team: "INT", role: "CENTROCAMPISTI", value: 38, age: 32, titolarita: 5, maxSpend: 40, valCarmy: 46, valProfeta: 36, valTattico: 39, notes: "" },
  { id: "p225", name: "MCTOMINAY", team: "NAP", role: "CENTROCAMPISTI", value: 38, age: 30, titolarita: 5, maxSpend: 43, valCarmy: 40, valProfeta: 42, valTattico: 48, notes: "" },
  { id: "p226", name: "RABIOT", team: "MIL", role: "CENTROCAMPISTI", value: 32, age: 31, titolarita: 5, maxSpend: 21, valCarmy: 25, valProfeta: 18, valTattico: 21, notes: "" },
  { id: "p227", name: "BATURINA", team: "COM", role: "CENTROCAMPISTI", value: 31, age: 23, titolarita: 4, maxSpend: 25, valCarmy: 24, valProfeta: 30, valTattico: 21, notes: "" },
  { id: "p228", name: "DE BRUYNE", team: "NAP", role: "CENTROCAMPISTI", value: 31, age: 35, titolarita: 4, maxSpend: 21, valCarmy: 22, valProfeta: 21, valTattico: 21, notes: "" },
  { id: "p229", name: "DIMARCO", team: "INT", role: "CENTROCAMPISTI", value: 30, age: 29, altRole: "DIFENSORI", titolarita: 5, maxSpend: 45, valCarmy: 45, valProfeta: 45, valTattico: 45, notes: "" },
  { id: "p230", name: "BARELLA", team: "INT", role: "CENTROCAMPISTI", value: 26, age: 29, titolarita: 4, maxSpend: 20, valCarmy: 19, valProfeta: 20, valTattico: 21, notes: "" },
  { id: "p231", name: "DA CUNHA", team: "COM", role: "CENTROCAMPISTI", value: 26, age: 25, titolarita: 5, maxSpend: 22, valCarmy: 23, valProfeta: 21, valTattico: 21, notes: "" },
  { id: "p232", name: "MCKENNIE", team: "JUV", role: "CENTROCAMPISTI", value: 24, age: 28, titolarita: 5, maxSpend: 18, valCarmy: 17, valProfeta: 15, valTattico: 21, notes: "" },
  { id: "p233", name: "VLASIC", team: "TOR", role: "CENTROCAMPISTI", value: 24, age: 29, titolarita: 5, maxSpend: 19, valCarmy: 17, valProfeta: 18, valTattico: 21, notes: "" },
  { id: "p234", name: "ATTA", team: "FIO", role: "CENTROCAMPISTI", value: 23, age: 23, titolarita: 5, maxSpend: 23, valCarmy: 22, valProfeta: 24, valTattico: 24, notes: "" },
  { id: "p235", name: "MASTANTUONO", team: "FIO", role: "CENTROCAMPISTI", value: 23, age: 19, titolarita: 4, maxSpend: 20, valCarmy: 17, valProfeta: 20, valTattico: 24, notes: "" },
  { id: "p236", name: "CONCEICAO", team: "JUV", role: "CENTROCAMPISTI", value: 22, age: 24, titolarita: 4, maxSpend: 16, valCarmy: 21, valProfeta: 12, valTattico: 15, notes: "" },
  { id: "p237", name: "EDERSON", team: "ATA", role: "CENTROCAMPISTI", value: 21, age: 27, titolarita: 5, maxSpend: 13, valCarmy: 11, valProfeta: 12, valTattico: 15, notes: "" },
  { id: "p238", name: "MODRIC", team: "MIL", role: "CENTROCAMPISTI", value: 21, age: 41, titolarita: 4, maxSpend: 9, valCarmy: 8, valProfeta: 7, valTattico: 12, notes: "" },
  { id: "p239", name: "MOLINA", team: "ROM", role: "CENTROCAMPISTI", value: 21, age: 28, altRole: "DIFENSORI", titolarita: 4, maxSpend: 18, valCarmy: 19, valProfeta: 16, valTattico: 18, notes: "" },
  { id: "p240", name: "WESLEY", team: "ROM", role: "CENTROCAMPISTI", value: 21, age: 23, altRole: "DIFENSORI", titolarita: 5, maxSpend: 23, valCarmy: 23, valProfeta: 24, valTattico: 21, notes: "" },
  { id: "p241", name: "KONE", team: "ROM", role: "CENTROCAMPISTI", value: 20, age: 25, titolarita: 5, maxSpend: 7, valCarmy: 10, valProfeta: 6, valTattico: 6, notes: "" },
  { id: "p242", name: "PELLEGRINI", team: "ROM", role: "CENTROCAMPISTI", value: 20, age: 30, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p243", name: "TAYLOR", team: "LAZ", role: "CENTROCAMPISTI", value: 20, age: 24, titolarita: 5, maxSpend: 11, valCarmy: 10, valProfeta: 12, valTattico: 12, notes: "" },
  { id: "p244", name: "ZIELINSKI", team: "INT", role: "CENTROCAMPISTI", value: 20, age: 32, titolarita: 3, maxSpend: 19, valCarmy: 23, valProfeta: 21, valTattico: 12, notes: "" },
  { id: "p245", name: "ANGUISSA", team: "NAP", role: "CENTROCAMPISTI", value: 19, age: 31, titolarita: 3, maxSpend: 6, valCarmy: 4, valProfeta: 9, valTattico: 6, notes: "" },
  { id: "p246", name: "DA SILVA MOREIRA", team: "MIL", role: "CENTROCAMPISTI", value: 19, age: 22, titolarita: 4, maxSpend: 16, valCarmy: 15, valProfeta: 16, valTattico: 18, notes: "" },
  { id: "p247", name: "SAMARDZIC", team: "ATA", role: "CENTROCAMPISTI", value: 19, age: 24, titolarita: 3, maxSpend: 11, valCarmy: 9, valProfeta: 10, valTattico: 14, notes: "" },
  { id: "p248", name: "JONES", team: "INT", role: "CENTROCAMPISTI", value: 18, age: 25, titolarita: 3, maxSpend: 11, valCarmy: 14, valProfeta: 9, valTattico: 9, notes: "" },
  { id: "p249", name: "SPENCE", team: "INT", role: "CENTROCAMPISTI", value: 18, age: 26, altRole: "DIFENSORI", titolarita: 3, maxSpend: 13, valCarmy: 11, valProfeta: 16, valTattico: 12, notes: "" },
  { id: "p250", name: "THURAM", team: "JUV", role: "CENTROCAMPISTI", value: 18, age: 25, titolarita: 3, maxSpend: 4, valCarmy: 4, valProfeta: 3, valTattico: 6, notes: "" },
  { id: "p251", name: "BALDANZI", team: "GEN", role: "CENTROCAMPISTI", value: 17, age: 23, titolarita: 4, maxSpend: 6, valCarmy: 7, valProfeta: 5, valTattico: 6, notes: "" },
  { id: "p252", name: "CASADEI", team: "TOR", role: "CENTROCAMPISTI", value: 17, age: 23, titolarita: 3, maxSpend: 8, valCarmy: 5, valProfeta: 12, valTattico: 6, notes: "" },
  { id: "p253", name: "PERRONE", team: "COM", role: "CENTROCAMPISTI", value: 17, age: 23, titolarita: 4, maxSpend: 4, valCarmy: 2, valProfeta: 2, valTattico: 8, notes: "" },
  { id: "p254", name: "SAELEMAEKERS", team: "MIL", role: "CENTROCAMPISTI", value: 17, age: 27, titolarita: 3, maxSpend: 10, valCarmy: 8, valProfeta: 9, valTattico: 12, notes: "" },
  { id: "p255", name: "THORSTVEDT", team: "SAS", role: "CENTROCAMPISTI", value: 17, age: 27, titolarita: 5, maxSpend: 5, valCarmy: 2, valProfeta: 3, valTattico: 9, notes: "" },
  { id: "p256", name: "EKKELENKAMP", team: "UDI", role: "CENTROCAMPISTI", value: 16, age: 26, titolarita: 5, maxSpend: 11, valCarmy: 13, valProfeta: 15, valTattico: 6, notes: "" },
  { id: "p257", name: "PASALIC", team: "ATA", role: "CENTROCAMPISTI", value: 16, age: 31, titolarita: 3, maxSpend: 3, valCarmy: 4, valProfeta: 3, valTattico: 1, notes: "" },
  { id: "p258", name: "SUCIC", team: "INT", role: "CENTROCAMPISTI", value: 16, age: 23, titolarita: 3, maxSpend: 4, valCarmy: 1, valProfeta: 5, valTattico: 6, notes: "" },
  { id: "p259", name: "CAMBIASO", team: "JUV", role: "CENTROCAMPISTI", value: 15, age: 26, altRole: "DIFENSORI", titolarita: 3, maxSpend: 5, valCarmy: 5, valProfeta: 4, valTattico: 6, notes: "" },
  { id: "p260", name: "ELMAS", team: "ATA", role: "CENTROCAMPISTI", value: 15, age: 27, titolarita: 2, maxSpend: 2, valCarmy: 2, valProfeta: 3, valTattico: 1, notes: "" },
  { id: "p261", name: "FAGIOLI", team: "FIO", role: "CENTROCAMPISTI", value: 15, age: 25, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p262", name: "MANDRAGORA", team: "FIO", role: "CENTROCAMPISTI", value: 15, age: 29, titolarita: 2, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p263", name: "VERGARA", team: "NAP", role: "CENTROCAMPISTI", value: 15, age: 23, titolarita: 3, maxSpend: 9, valCarmy: 13, valProfeta: 12, valTattico: 3, notes: "" },
  { id: "p264", name: "BERNABE", team: "PAR", role: "CENTROCAMPISTI", value: 14, age: 25, titolarita: 5, maxSpend: 4, valCarmy: 6, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p265", name: "CRISTANTE", team: "ROM", role: "CENTROCAMPISTI", value: 14, age: 31, titolarita: 5, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p266", name: "FERGUSON", team: "BOL", role: "CENTROCAMPISTI", value: 14, age: 27, titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p267", name: "FRATTESI", team: "LAZ", role: "CENTROCAMPISTI", value: 14, age: 27, titolarita: 4, maxSpend: 11, valCarmy: 12, valProfeta: 13, valTattico: 9, notes: "" },
  { id: "p268", name: "GAETANO", team: "ATA", role: "CENTROCAMPISTI", value: 14, age: 26, titolarita: 4, maxSpend: 4, valCarmy: 3, valProfeta: 5, valTattico: 3, notes: "" },
  { id: "p269", name: "KONE", team: "SAS", role: "CENTROCAMPISTI", value: 14, age: 24, titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p270", name: "LOBOTKA", team: "NAP", role: "CENTROCAMPISTI", value: 14, age: 32, titolarita: 5, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p271", name: "LOCATELLI", team: "JUV", role: "CENTROCAMPISTI", value: 14, age: 28, titolarita: 5, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p272", name: "SOW", team: "GEN", role: "CENTROCAMPISTI", value: 14, age: 29, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 4, valTattico: 1, notes: "" },
  { id: "p273", name: "CAQUERET", team: "COM", role: "CENTROCAMPISTI", value: 13, age: 26, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 2, valTattico: 0, notes: "" },
  { id: "p274", name: "COLPANI", team: "MON", role: "CENTROCAMPISTI", value: 13, age: 27, titolarita: 3, maxSpend: 3, valCarmy: 2, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p275", name: "DODO", team: "FIO", role: "CENTROCAMPISTI", value: 13, age: 28, altRole: "DIFENSORI", titolarita: 2, maxSpend: 5, valCarmy: 2, valProfeta: 3, valTattico: 9, notes: "" },
  { id: "p276", name: "NDOUR", team: "FIO", role: "CENTROCAMPISTI", value: 13, age: 22, titolarita: 4, maxSpend: 4, valCarmy: 1, valProfeta: 8, valTattico: 3, notes: "" },
  { id: "p277", name: "PISILLI", team: "ROM", role: "CENTROCAMPISTI", value: 13, age: 22, titolarita: 3, maxSpend: 4, valCarmy: 3, valProfeta: 7, valTattico: 3, notes: "" },
  { id: "p278", name: "SCHMID", team: "FRO", role: "CENTROCAMPISTI", value: 13, age: 26, titolarita: 4, maxSpend: 3, valCarmy: 1, valProfeta: 3, valTattico: 5, notes: "" },
  { id: "p279", name: "UNAI GOMEZ", team: "UDI", role: "CENTROCAMPISTI", value: 13, age: 23, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p280", name: "VOLPATO", team: "SAS", role: "CENTROCAMPISTI", value: 13, age: 23, titolarita: 3, maxSpend: 2, valCarmy: 2, valProfeta: 5, valTattico: 0, notes: "" },
  { id: "p281", name: "ZAPPACOSTA", team: "ATA", role: "CENTROCAMPISTI", value: 13, age: 34, altRole: "DIFENSORI", titolarita: 4, maxSpend: 8, valCarmy: 10, valProfeta: 9, valTattico: 6, notes: "" },
  { id: "p282", name: "CALO", team: "FRO", role: "CENTROCAMPISTI", value: 12, age: 29, titolarita: 4, maxSpend: 7, valCarmy: 10, valProfeta: 4, valTattico: 6, notes: "" },
  { id: "p283", name: "CHUKWUEZE", team: "MIL", role: "CENTROCAMPISTI", value: 12, age: 27, titolarita: 3, maxSpend: 5, valCarmy: 10, valProfeta: 5, valTattico: 1, notes: "" },
  { id: "p284", name: "FRENDRUP", team: "GEN", role: "CENTROCAMPISTI", value: 12, age: 25, titolarita: 5, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p285", name: "KARLSTROM", team: "UDI", role: "CENTROCAMPISTI", value: 12, age: 31, titolarita: 5, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p286", name: "MKHITARYAN", team: "INT", role: "CENTROCAMPISTI", value: 12, age: 37, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p287", name: "PESSINA", team: "MON", role: "CENTROCAMPISTI", value: 12, age: 29, titolarita: 5, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p288", name: "SPINAZZOLA", team: "NAP", role: "CENTROCAMPISTI", value: 12, age: 33, altRole: "DIFENSORI", titolarita: 4, maxSpend: 8, valCarmy: 11, valProfeta: 6, valTattico: 6, notes: "" },
  { id: "p289", name: "ZALEWSKI", team: "ATA", role: "CENTROCAMPISTI", value: 12, age: 24, titolarita: 3, maxSpend: 2, valCarmy: 4, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p290", name: "ADOPO", team: "CAG", role: "CENTROCAMPISTI", value: 11, age: 26, titolarita: 5, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p291", name: "BUSIO", team: "VEN", role: "CENTROCAMPISTI", value: 11, age: 24, titolarita: 5, maxSpend: 2, valCarmy: 2, valProfeta: 4, valTattico: 1, notes: "" },
  { id: "p292", name: "DIOUF", team: "INT", role: "CENTROCAMPISTI", value: 11, age: 23, titolarita: 3, maxSpend: 12, valCarmy: 18, valProfeta: 8, valTattico: 9, notes: "" },
  { id: "p293", name: "FAZZINI", team: "CAG", role: "CENTROCAMPISTI", value: 11, age: 23, titolarita: 4, maxSpend: 5, valCarmy: 4, valProfeta: 5, valTattico: 6, notes: "" },
  { id: "p294", name: "MATIC", team: "SAS", role: "CENTROCAMPISTI", value: 11, age: 38, titolarita: 5, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p295", name: "POBEGA", team: "BOL", role: "CENTROCAMPISTI", value: 11, age: 27, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p296", name: "ZHEGROVA", team: "JUV", role: "CENTROCAMPISTI", value: 11, age: 27, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p297", name: "BASIC", team: "VEN", role: "CENTROCAMPISTI", value: 10, age: 30, titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p298", name: "CARLOS AUGUSTO", team: "INT", role: "CENTROCAMPISTI", value: 10, age: 27, altRole: "DIFENSORI", titolarita: 3, maxSpend: 4, valCarmy: 4, valProfeta: 3, valTattico: 6, notes: "" },
  { id: "p299", name: "COULIBALY", team: "LEC", role: "CENTROCAMPISTI", value: 10, age: 30, titolarita: 5, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p300", name: "DE ROON", team: "ROM", role: "CENTROCAMPISTI", value: 10, age: 35, titolarita: 3, maxSpend: 1, valCarmy: 1, notes: "" },
  { id: "p301", name: "ELLERTSSON", team: "GEN", role: "CENTROCAMPISTI", value: 10, age: 24, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p302", name: "FOFANA", team: "MIL", role: "CENTROCAMPISTI", value: 10, age: 27, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p303", name: "GANDELMAN", team: "LEC", role: "CENTROCAMPISTI", value: 10, age: 26, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p304", name: "GINEITIS", team: "TOR", role: "CENTROCAMPISTI", value: 10, age: 22, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p305", name: "JASHARI", team: "MIL", role: "CENTROCAMPISTI", value: 10, age: 24, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p306", name: "KAMARA", team: "UDI", role: "CENTROCAMPISTI", value: 10, age: 32, altRole: "DIFENSORI", titolarita: 3, maxSpend: 3, valCarmy: 1, valProfeta: 4, valTattico: 3, notes: "" },
  { id: "p307", name: "KEITA", team: "PAR", role: "CENTROCAMPISTI", value: 10, age: 24, titolarita: 5, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p308", name: "KOOPMEINERS", team: "JUV", role: "CENTROCAMPISTI", value: 10, age: 28, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p309", name: "LIBERALI", team: "COM", role: "CENTROCAMPISTI", value: 10, age: 19, titolarita: 3, maxSpend: 4, valCarmy: 6, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p310", name: "MILLA", team: "COM", role: "CENTROCAMPISTI", value: 10, age: 32, titolarita: 3, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p311", name: "NICOLUSSI CAVIGL.", team: "PAR", role: "CENTROCAMPISTI", value: 10, age: 26, maxSpend: 1, notes: "" },
  { id: "p312", name: "NORTON-CUFFY", team: "GEN", role: "CENTROCAMPISTI", value: 10, age: 22, altRole: "DIFENSORI", titolarita: 5, maxSpend: 6, valCarmy: 5, valProfeta: 5, valTattico: 9, notes: "" },
  { id: "p313", name: "OULAI", team: "FIO", role: "CENTROCAMPISTI", value: 10, age: 20, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p314", name: "PEREZ", team: "VEN", role: "CENTROCAMPISTI", value: 10, age: 29, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p315", name: "ROVELLA", team: "LAZ", role: "CENTROCAMPISTI", value: 10, age: 25, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p316", name: "TRAORE", team: "GEN", role: "CENTROCAMPISTI", value: 10, age: 26, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p317", name: "WINKS", team: "CAG", role: "CENTROCAMPISTI", value: 10, age: 30, titolarita: 4, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p318", name: "AHANOR", team: "ATA", role: "CENTROCAMPISTI", value: 9, age: 18, altRole: "DIFENSORI", titolarita: 1, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p319", name: "BELLANOVA", team: "ATA", role: "CENTROCAMPISTI", value: 9, age: 26, altRole: "DIFENSORI", titolarita: 3, maxSpend: 3, valCarmy: 1, valProfeta: 1, valTattico: 6, notes: "" },
  { id: "p320", name: "BERNASCONI", team: "ATA", role: "CENTROCAMPISTI", value: 9, age: 23, altRole: "DIFENSORI", titolarita: 5, maxSpend: 5, valCarmy: 5, valProfeta: 4, valTattico: 6, notes: "" },
  { id: "p321", name: "DELE-BASHIRU", team: "LAZ", role: "CENTROCAMPISTI", value: 9, age: 25, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p322", name: "FELICI", team: "CAG", role: "CENTROCAMPISTI", value: 9, age: 25, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p323", name: "KRISTENSEN", team: "ATA", role: "CENTROCAMPISTI", value: 9, age: 24, altRole: "DIFENSORI", titolarita: 3, maxSpend: 6, valCarmy: 1, valProfeta: 12, valTattico: 6, notes: "" },
  { id: "p324", name: "LOFTUS-CHEEK", team: "MIL", role: "CENTROCAMPISTI", value: 9, age: 30, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p325", name: "LUIS HENRIQUE", team: "INT", role: "CENTROCAMPISTI", value: 9, age: 25, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p326", name: "MARTIN", team: "GEN", role: "CENTROCAMPISTI", value: 9, age: 29, altRole: "DIFENSORI", titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p327", name: "MORO", team: "BOL", role: "CENTROCAMPISTI", value: 9, age: 28, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p328", name: "PIOTROWSKI", team: "UDI", role: "CENTROCAMPISTI", value: 9, age: 29, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p329", name: "ROMANO", team: "CAG", role: "CENTROCAMPISTI", value: 9, age: 20, titolarita: 5, maxSpend: 2, valCarmy: 2, valProfeta: 3, valTattico: 1, notes: "" },
  { id: "p330", name: "ZORTEA", team: "BOL", role: "CENTROCAMPISTI", value: 9, age: 27, altRole: "DIFENSORI", titolarita: 3, maxSpend: 4, valCarmy: 2, valProfeta: 3, valTattico: 6, notes: "" },
  { id: "p331", name: "AKINSANMIRO", team: "MON", role: "CENTROCAMPISTI", value: 8, age: 22, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p332", name: "AMORIM", team: "GEN", role: "CENTROCAMPISTI", value: 8, age: 21, titolarita: 3, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p333", name: "BERISHA", team: "LEC", role: "CENTROCAMPISTI", value: 8, age: 23, titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p334", name: "CATALDI", team: "LAZ", role: "CENTROCAMPISTI", value: 8, age: 32, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p335", name: "FABBIAN", team: "PAR", role: "CENTROCAMPISTI", value: 8, age: 23, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p336", name: "FAVASULI", team: "NAP", role: "CENTROCAMPISTI", value: 8, age: 22, altRole: "DIFENSORI", titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p337", name: "GRILLITSCH", team: "FRO", role: "CENTROCAMPISTI", value: 8, age: 31, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p338", name: "ILKHAN", team: "TOR", role: "CENTROCAMPISTI", value: 8, age: 22, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p339", name: "KOUTSOUPIAS", team: "FRO", role: "CENTROCAMPISTI", value: 8, age: 25, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p340", name: "MEICHTRY", team: "GEN", role: "CENTROCAMPISTI", value: 8, age: 21, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 2, valTattico: 1, notes: "" },
  { id: "p341", name: "OLIVERA", team: "NAP", role: "CENTROCAMPISTI", value: 8, age: 29, altRole: "DIFENSORI", titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 1, notes: "" },
  { id: "p342", name: "SOHM", team: "VEN", role: "CENTROCAMPISTI", value: 8, age: 25, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p343", name: "TOURE", team: "MON", role: "CENTROCAMPISTI", value: 8, age: 28, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 2, notes: "" },
  { id: "p344", name: "ZERBIN", team: "FRO", role: "CENTROCAMPISTI", value: 8, age: 27, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p345", name: "ADZIC", team: "SAS", role: "CENTROCAMPISTI", value: 7, age: 20, titolarita: 3, maxSpend: 4, valCarmy: 2, valProfeta: 7, valTattico: 2, notes: "" },
  { id: "p346", name: "AMONDARAIN", team: "BOL", role: "CENTROCAMPISTI", value: 7, age: 21, titolarita: 3, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p347", name: "BAKOLA", team: "SAS", role: "CENTROCAMPISTI", value: 7, age: 19, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 2, notes: "" },
  { id: "p348", name: "BONDO", team: "MIL", role: "CENTROCAMPISTI", value: 7, age: 23, notes: "" },
  { id: "p349", name: "BRESCIANINI", team: "FIO", role: "CENTROCAMPISTI", value: 7, age: 26, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p350", name: "CACCIAMANI", team: "TOR", role: "CENTROCAMPISTI", value: 7, age: 19, titolarita: 4, maxSpend: 3, valCarmy: 1, valProfeta: 5, valTattico: 3, notes: "" },
  { id: "p351", name: "CICHELLA", team: "FRO", role: "CENTROCAMPISTI", value: 7, age: 21, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p352", name: "DOUGLAS LUIZ", team: "JUV", role: "CENTROCAMPISTI", value: 7, age: 28, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 2, notes: "" },
  { id: "p353", name: "EL AYNAOUI", team: "ROM", role: "CENTROCAMPISTI", value: 7, age: 25, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p354", name: "FADERA", team: "CAG", role: "CENTROCAMPISTI", value: 7, age: 25, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p355", name: "FITZ-JIM", team: "TOR", role: "CENTROCAMPISTI", value: 7, age: 23, titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p356", name: "FOLORUNSHO", team: "MON", role: "CENTROCAMPISTI", value: 7, age: 28, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 2, notes: "" },
  { id: "p357", name: "GILMOUR", team: "NAP", role: "CENTROCAMPISTI", value: 7, age: 25, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p358", name: "MANGAS", team: "MON", role: "CENTROCAMPISTI", value: 7, age: 28, altRole: "DIFENSORI", titolarita: 5, maxSpend: 2, valCarmy: 3, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p359", name: "NGOM", team: "LEC", role: "CENTROCAMPISTI", value: 7, age: 22, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p360", name: "PARISI", team: "FIO", role: "CENTROCAMPISTI", value: 7, age: 26, altRole: "DIFENSORI", titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p361", name: "RICCI", team: "COM", role: "CENTROCAMPISTI", value: 7, age: 25, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p362", name: "SORENSEN", team: "PAR", role: "CENTROCAMPISTI", value: 7, age: 24, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p363", name: "SULEMANA I", team: "ATA", role: "CENTROCAMPISTI", value: 7, age: 23, titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p364", name: "BIRINDELLI", team: "MON", role: "CENTROCAMPISTI", value: 6, age: 27, altRole: "DIFENSORI", titolarita: 5, maxSpend: 2, valCarmy: 2, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p365", name: "CIURRIA", team: "MON", role: "CENTROCAMPISTI", value: 6, age: 31, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p366", name: "COLOMBO", team: "MON", role: "CENTROCAMPISTI", value: 6, age: 21, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p367", name: "GELLI", team: "FRO", role: "CENTROCAMPISTI", value: 6, age: 30, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p368", name: "HAPS", team: "VEN", role: "CENTROCAMPISTI", value: 6, age: 33, altRole: "DIFENSORI", titolarita: 4, maxSpend: 2, valCarmy: 3, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p369", name: "JOAO MARIO", team: "FIO", role: "CENTROCAMPISTI", value: 6, age: 26, altRole: "DIFENSORI", titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 5, valTattico: 1, notes: "" },
  { id: "p370", name: "LOVRIC", team: "UDI", role: "CENTROCAMPISTI", value: 6, age: 28, notes: "" },
  { id: "p371", name: "MALEH", team: "LEC", role: "CENTROCAMPISTI", value: 6, age: 28, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p372", name: "MAZZITELLI", team: "COM", role: "CENTROCAMPISTI", value: 6, age: 31, notes: "" },
  { id: "p373", name: "MESSIAS", team: "GEN", role: "CENTROCAMPISTI", value: 6, age: 35, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p374", name: "MILLER", team: "UDI", role: "CENTROCAMPISTI", value: 6, age: 20, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p375", name: "STANKOVIC", team: "INT", role: "CENTROCAMPISTI", value: 6, age: 21, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p376", name: "TERRACCIANO F", team: "MIL", role: "CENTROCAMPISTI", value: 6, age: 23, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p377", name: "VENTURINO", team: "GEN", role: "CENTROCAMPISTI", value: 6, age: 20, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p378", name: "ARIZALA", team: "UDI", role: "CENTROCAMPISTI", value: 5, age: 21, altRole: "DIFENSORI", titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p379", name: "BOLOCA", team: "SAS", role: "CENTROCAMPISTI", value: 5, age: 28, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p380", name: "COMOTTO", team: "MIL", role: "CENTROCAMPISTI", value: 5, age: 18, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p381", name: "DEIOLA", team: "CAG", role: "CENTROCAMPISTI", value: 5, age: 31, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p382", name: "DUNCAN", team: "VEN", role: "CENTROCAMPISTI", value: 5, age: 33, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p383", name: "FORTINI", team: "TOR", role: "CENTROCAMPISTI", value: 5, age: 20, altRole: "DIFENSORI", titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 2, notes: "" },
  { id: "p384", name: "GORTER", team: "LEC", role: "CENTROCAMPISTI", value: 5, age: 21, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p385", name: "HASA", team: "FRO", role: "CENTROCAMPISTI", value: 5, age: 22, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p386", name: "HELGASON", team: "VEN", role: "CENTROCAMPISTI", value: 5, age: 26, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p387", name: "LIPANI", team: "SAS", role: "CENTROCAMPISTI", value: 5, age: 21, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p388", name: "MASINI", team: "FRO", role: "CENTROCAMPISTI", value: 5, age: 25, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p389", name: "MUSAH", team: "MIL", role: "CENTROCAMPISTI", value: 5, age: 24, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p390", name: "ORDONEZ", team: "PAR", role: "CENTROCAMPISTI", value: 5, age: 22, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p391", name: "SALAH-EDDINE", team: "ROM", role: "CENTROCAMPISTI", value: 5, age: 24, notes: "" },
  { id: "p392", name: "ZANOLI", team: "UDI", role: "CENTROCAMPISTI", value: 5, age: 26, altRole: "DIFENSORI", titolarita: 1, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p393", name: "ANJORIN", team: "TOR", role: "CENTROCAMPISTI", value: 4, age: 25, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p394", name: "AURELIO", team: "CAG", role: "CENTROCAMPISTI", value: 4, age: 26, altRole: "DIFENSORI", titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p395", name: "BIRAGHI", team: "TOR", role: "CENTROCAMPISTI", value: 4, age: 34, altRole: "DIFENSORI", titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p396", name: "CABAL", team: "JUV", role: "CENTROCAMPISTI", value: 4, age: 25, altRole: "DIFENSORI", titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p397", name: "CHAKVETADZE", team: "UDI", role: "CENTROCAMPISTI", value: 4, age: 27, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p398", name: "EL AZZOUZI", team: "BOL", role: "CENTROCAMPISTI", value: 4, age: 25, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p399", name: "FLORIANI MUSSOLI.", team: "LAZ", role: "CENTROCAMPISTI", value: 4, age: 23, maxSpend: 1, altRole: "DIFENSORI", notes: "" },
  { id: "p400", name: "FORSON", team: "MON", role: "CENTROCAMPISTI", value: 4, age: 22, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p401", name: "IDRISSI", team: "CAG", role: "CENTROCAMPISTI", value: 4, age: 21, altRole: "DIFENSORI", titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p402", name: "ILIC", team: "LEC", role: "CENTROCAMPISTI", value: 4, age: 25, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 2, valTattico: 0, notes: "" },
  { id: "p403", name: "MASSOLIN", team: "INT", role: "CENTROCAMPISTI", value: 4, age: 24, notes: "" },
  { id: "p404", name: "SABELLI", team: "GEN", role: "CENTROCAMPISTI", value: 4, age: 33, altRole: "DIFENSORI", titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p405", name: "SAGRADO", team: "VEN", role: "CENTROCAMPISTI", value: 4, age: 22, altRole: "DIFENSORI", titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p406", name: "BAKOUNE", team: "MON", role: "CENTROCAMPISTI", value: 3, age: 20, altRole: "DIFENSORI", titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p407", name: "BELAHYANE", team: "LAZ", role: "CENTROCAMPISTI", value: 3, age: 22, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p409", name: "CIERVO", team: "CAG", role: "CENTROCAMPISTI", value: 3, age: 24, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p410", name: "CREMASCHI", team: "PAR", role: "CENTROCAMPISTI", value: 3, age: 21, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p411", name: "FOE ONDOA", team: "MON", role: "CENTROCAMPISTI", value: 3, age: 21, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p412", name: "GHION", team: "SAS", role: "CENTROCAMPISTI", value: 3, age: 26, notes: "" },
  { id: "p413", name: "KONE", team: "FRO", role: "CENTROCAMPISTI", value: 3, age: 26, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p414", name: "MAZZOCCHI", team: "NAP", role: "CENTROCAMPISTI", value: 3, age: 31, altRole: "DIFENSORI", titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p415", name: "ZARRAGA", team: "UDI", role: "CENTROCAMPISTI", value: 3, age: 27, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p416", name: "BAKKER", team: "ATA", role: "CENTROCAMPISTI", value: 2, age: 26, notes: "" },
  { id: "p417", name: "BRAUNODER", team: "COM", role: "CENTROCAMPISTI", value: 2, age: 24, notes: "" },
  { id: "p418", name: "DEMBELE", team: "LEC", role: "CENTROCAMPISTI", value: 2, age: 22, notes: "" },
  { id: "p419", name: "FOFANA", team: "LEC", role: "CENTROCAMPISTI", value: 2, age: 23, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p420", name: "GALAZZI", team: "MON", role: "CENTROCAMPISTI", value: 2, age: 26, notes: "" },
  { id: "p421", name: "IANNONI", team: "SAS", role: "CENTROCAMPISTI", value: 2, age: 25, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p422", name: "KABA", team: "LEC", role: "CENTROCAMPISTI", value: 2, age: 25, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p423", name: "LULLI", team: "ROM", role: "CENTROCAMPISTI", value: 2, age: 19, altRole: "DIFENSORI", titolarita: 3, maxSpend: 1, valCarmy: 3, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p424", name: "LUONGO", team: "TOR", role: "CENTROCAMPISTI", value: 2, age: 18, notes: "" },
  { id: "p425", name: "MOUT", team: "MON", role: "CENTROCAMPISTI", value: 2, age: 19, titolarita: 3, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p426", name: "RUI MODESTO", team: "UDI", role: "CENTROCAMPISTI", value: 2, age: 27, notes: "" },
  { id: "p427", name: "AKARAKIRI", team: "CAG", role: "CENTROCAMPISTI", value: 1, age: 18, notes: "" },
  { id: "p428", name: "CAVUOTI", team: "CAG", role: "CENTROCAMPISTI", value: 1, age: 23, notes: "" },
  { id: "p429", name: "DAGASSO", team: "VEN", role: "CENTROCAMPISTI", value: 1, age: 22, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p430", name: "EL AZZOUZI", team: "FRO", role: "CENTROCAMPISTI", value: 1, age: 25, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p431", name: "FARCOMENI", team: "LAZ", role: "CENTROCAMPISTI", value: 1, age: 20, notes: "" },
  { id: "p432", name: "GALASSI", team: "LAZ", role: "CENTROCAMPISTI", value: 1, age: 19, notes: "" },
  { id: "p433", name: "KONATE", team: "PAR", role: "CENTROCAMPISTI", value: 1, age: 20, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p434", name: "KOVAC", team: "LEC", role: "CENTROCAMPISTI", value: 1, age: 21, notes: "" },
  { id: "p435", name: "LAHDO", team: "COM", role: "CENTROCAMPISTI", value: 1, age: 19, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p436", name: "LITETA", team: "CAG", role: "CENTROCAMPISTI", value: 1, age: 20, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p437", name: "PRZYBOREK", team: "LAZ", role: "CENTROCAMPISTI", value: 1, age: 19, titolarita: 1, maxSpend: 0, valCarmy: 0, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p438", name: "WIAFE", team: "GEN", role: "CENTROCAMPISTI", value: 1, age: 18, notes: "" },
  { id: "p439", name: "DABO", team: "VEN", role: "CENTROCAMPISTI", value: 0, age: 22, notes: "" },
  { id: "p563", name: "KESSIE", team: "ATA", role: "CENTROCAMPISTI", value: 17, age: 30, titolarita: 3, maxSpend: 2, valCarmy: 0, valProfeta: 0, valTattico: 6, notes: "" },
  { id: "p440", name: "MALEN", team: "ROM", role: "ATTACCANTI", value: 58, age: 27, titolarita: 5, maxSpend: 101, valCarmy: 105, valProfeta: 100, valTattico: 99, notes: "" },
  { id: "p441", name: "MARTINEZ L", team: "INT", role: "ATTACCANTI", value: 54, age: 29, titolarita: 5, maxSpend: 91, valCarmy: 90, valProfeta: 84, valTattico: 99, notes: "" },
  { id: "p442", name: "HOJLUND", team: "NAP", role: "ATTACCANTI", value: 46, age: 23, titolarita: 4, maxSpend: 57, valCarmy: 57, valProfeta: 60, valTattico: 54, notes: "" },
  { id: "p443", name: "RAMOS", team: "MIL", role: "ATTACCANTI", value: 46, age: 25, titolarita: 5, maxSpend: 68, valCarmy: 72, valProfeta: 60, valTattico: 72, notes: "" },
  { id: "p444", name: "THURAM", team: "INT", role: "ATTACCANTI", value: 46, age: 29, titolarita: 4, maxSpend: 64, valCarmy: 66, valProfeta: 57, valTattico: 69, notes: "" },
  { id: "p445", name: "KOLO MUANI", team: "JUV", role: "ATTACCANTI", value: 43, age: 28, titolarita: 5, maxSpend: 61, valCarmy: 75, valProfeta: 54, valTattico: 54, notes: "" },
  { id: "p446", name: "PAZ", team: "COM", role: "ATTACCANTI", value: 42, age: 22, altRole: "CENTROCAMPISTI", titolarita: 5, maxSpend: 49, valCarmy: 49, valProfeta: 45, valTattico: 54, notes: "" },
  { id: "p447", name: "KEAN", team: "FIO", role: "ATTACCANTI", value: 41, age: 26, titolarita: 3, maxSpend: 47, valCarmy: 42, valProfeta: 54, valTattico: 45, notes: "" },
  { id: "p448", name: "DOUVIKAS", team: "COM", role: "ATTACCANTI", value: 37, age: 27, titolarita: 3, maxSpend: 39, valCarmy: 48, valProfeta: 39, valTattico: 30, notes: "" },
  { id: "p449", name: "PULISIC", team: "MIL", role: "ATTACCANTI", value: 37, age: 28, altRole: "CENTROCAMPISTI", titolarita: 5, maxSpend: 30, valCarmy: 34, valProfeta: 33, valTattico: 24, notes: "" },
  { id: "p450", name: "YILDIZ", team: "JUV", role: "ATTACCANTI", value: 35, age: 21, titolarita: 5, maxSpend: 23, valCarmy: 21, valProfeta: 23, valTattico: 24, notes: "" },
  { id: "p451", name: "ORSOLINI", team: "BOL", role: "ATTACCANTI", value: 34, age: 29, altRole: "CENTROCAMPISTI", titolarita: 5, maxSpend: 40, valCarmy: 40, valProfeta: 39, valTattico: 42, notes: "" },
  { id: "p452", name: "SCAMACCA", team: "ATA", role: "ATTACCANTI", value: 34, age: 27, titolarita: 3, maxSpend: 38, valCarmy: 37, valProfeta: 36, valTattico: 42, notes: "" },
  { id: "p453", name: "DAVIS", team: "UDI", role: "ATTACCANTI", value: 32, age: 28, titolarita: 5, maxSpend: 33, valCarmy: 34, valProfeta: 36, valTattico: 30, notes: "" },
  { id: "p454", name: "KRSTOVIC", team: "ATA", role: "ATTACCANTI", value: 32, age: 26, titolarita: 3, maxSpend: 30, valCarmy: 30, valProfeta: 36, valTattico: 24, notes: "" },
  { id: "p455", name: "BERARDI", team: "SAS", role: "ATTACCANTI", value: 30, age: 32, titolarita: 5, maxSpend: 27, valCarmy: 24, valProfeta: 30, valTattico: 27, notes: "" },
  { id: "p456", name: "DYBALA", team: "ROM", role: "ATTACCANTI", value: 30, age: 33, titolarita: 5, maxSpend: 30, valCarmy: 31, valProfeta: 37, valTattico: 21, notes: "" },
  { id: "p457", name: "ESPOSITO FP", team: "INT", role: "ATTACCANTI", value: 29, age: 21, titolarita: 3, maxSpend: 30, valCarmy: 33, valProfeta: 40, valTattico: 17, notes: "" },
  { id: "p458", name: "DE KETELAERE", team: "ATA", role: "ATTACCANTI", value: 28, age: 25, titolarita: 4, maxSpend: 20, valCarmy: 21, valProfeta: 15, valTattico: 23, notes: "" },
  { id: "p459", name: "SIMEONE", team: "TOR", role: "ATTACCANTI", value: 28, age: 31, titolarita: 4, maxSpend: 33, valCarmy: 40, valProfeta: 30, valTattico: 30, notes: "" },
  { id: "p460", name: "ZANIOLO", team: "UDI", role: "ATTACCANTI", value: 28, age: 27, altRole: "CENTROCAMPISTI", titolarita: 5, maxSpend: 22, valCarmy: 19, valProfeta: 20, valTattico: 27, notes: "" },
  { id: "p461", name: "CASTRO", team: "ROM", role: "ATTACCANTI", value: 27, age: 22, titolarita: 3, maxSpend: 20, valCarmy: 14, valProfeta: 24, valTattico: 21, notes: "" },
  { id: "p462", name: "LAURIENTE", team: "SAS", role: "ATTACCANTI", value: 27, age: 28, titolarita: 5, maxSpend: 25, valCarmy: 29, valProfeta: 27, valTattico: 18, notes: "" },
  { id: "p463", name: "ZACCAGNI", team: "LAZ", role: "ATTACCANTI", value: 27, age: 31, altRole: "CENTROCAMPISTI", titolarita: 5, maxSpend: 22, valCarmy: 22, valProfeta: 18, valTattico: 27, notes: "" },
  { id: "p464", name: "PINAMONTI", team: "LAZ", role: "ATTACCANTI", value: 26, age: 27, titolarita: 3, maxSpend: 22, valCarmy: 19, valProfeta: 30, valTattico: 18, notes: "" },
  { id: "p465", name: "RASPADORI", team: "ATA", role: "ATTACCANTI", value: 25, age: 26, titolarita: 4, maxSpend: 17, valCarmy: 25, valProfeta: 15, valTattico: 12, notes: "" },
  { id: "p466", name: "GUDMUNDSSON", team: "FIO", role: "ATTACCANTI", value: 24, age: 29, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 13, valCarmy: 11, valProfeta: 9, valTattico: 18, notes: "" },
  { id: "p467", name: "DOVBYK", team: "BOL", role: "ATTACCANTI", value: 23, age: 29, titolarita: 3, maxSpend: 24, valCarmy: 23, valProfeta: 27, valTattico: 21, notes: "" },
  { id: "p468", name: "MORA CARVALHO", team: "ROM", role: "ATTACCANTI", value: 23, age: 19, titolarita: 4, maxSpend: 23, valCarmy: 26, valProfeta: 27, valTattico: 15, altRole: "CENTROCAMPISTI", notes: "" },
  { id: "p469", name: "SOULE", team: "ROM", role: "ATTACCANTI", value: 23, age: 23, titolarita: 4, maxSpend: 12, valCarmy: 10, valProfeta: 15, valTattico: 12, notes: "" },
  { id: "p470", name: "ESPOSITO S", team: "SAS", role: "ATTACCANTI", value: 22, age: 24, titolarita: 3, maxSpend: 9, valCarmy: 4, valProfeta: 10, valTattico: 12, notes: "" },
  { id: "p471", name: "DIAO", team: "COM", role: "ATTACCANTI", value: 21, age: 21, titolarita: 4, maxSpend: 14, valCarmy: 22, valProfeta: 11, valTattico: 9, notes: "" },
  { id: "p472", name: "RODRIGUEZ", team: "COM", role: "ATTACCANTI", value: 21, age: 21, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 9, valCarmy: 14, valProfeta: 3, valTattico: 9, notes: "" },
  { id: "p473", name: "ROWE", team: "BOL", role: "ATTACCANTI", value: 21, age: 23, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 17, valCarmy: 16, valProfeta: 18, valTattico: 18, notes: "" },
  { id: "p474", name: "ALAJBEGOVIC", team: "JUV", role: "ATTACCANTI", value: 20, age: 19, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 28, valCarmy: 25, valProfeta: 30, valTattico: 29, notes: "" },
  { id: "p475", name: "COLOMBO", team: "GEN", role: "ATTACCANTI", value: 20, age: 24, titolarita: 5, maxSpend: 20, valCarmy: 20, valProfeta: 21, valTattico: 18, notes: "" },
  { id: "p476", name: "POLITANO", team: "NAP", role: "ATTACCANTI", value: 20, age: 33, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 5, valCarmy: 5, valProfeta: 3, valTattico: 6, notes: "" },
  { id: "p477", name: "ADAMS", team: "TOR", role: "ATTACCANTI", value: 18, age: 30, titolarita: 2, maxSpend: 4, valCarmy: 1, valProfeta: 8, valTattico: 2, notes: "" },
  { id: "p478", name: "DAVID", team: "JUV", role: "ATTACCANTI", value: 18, age: 26, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p479", name: "BOWIE", team: "SAS", role: "ATTACCANTI", value: 16, age: 24, titolarita: 3, maxSpend: 11, valCarmy: 15, valProfeta: 15, valTattico: 2, notes: "" },
  { id: "p480", name: "PICCOLI", team: "BOL", role: "ATTACCANTI", value: 16, age: 25, titolarita: 3, maxSpend: 10, valCarmy: 11, valProfeta: 9, valTattico: 9, notes: "" },
  { id: "p481", name: "VITINHA", team: "GEN", role: "ATTACCANTI", value: 16, age: 26, titolarita: 5, maxSpend: 3, valCarmy: 1, valProfeta: 7, valTattico: 0, notes: "" },
  { id: "p482", name: "ZAPATA", team: "TOR", role: "ATTACCANTI", value: 16, age: 35, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 3, valTattico: 1, notes: "" },
  { id: "p483", name: "BONNY", team: "INT", role: "ATTACCANTI", value: 15, age: 23, titolarita: 2, maxSpend: 6, valCarmy: 5, valProfeta: 6, valTattico: 6, notes: "" },
  { id: "p484", name: "CUTRONE", team: "MON", role: "ATTACCANTI", value: 15, age: 28, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 2, notes: "" },
  { id: "p485", name: "ISAKSEN", team: "LAZ", role: "ATTACCANTI", value: 15, age: 25, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 7, valCarmy: 11, valProfeta: 3, valTattico: 6, notes: "" },
  { id: "p486", name: "KEVIN CARLOS", team: "CAG", role: "ATTACCANTI", value: 15, age: 25, titolarita: 4, maxSpend: 4, valCarmy: 2, valProfeta: 6, valTattico: 3, notes: "" },
  { id: "p487", name: "ODGAARD", team: "BOL", role: "ATTACCANTI", value: 15, age: 27, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p488", name: "RATKOV", team: "LAZ", role: "ATTACCANTI", value: 15, age: 23, titolarita: 2, maxSpend: 3, valCarmy: 1, valProfeta: 2, valTattico: 6, notes: "" },
  { id: "p489", name: "STULIC", team: "LEC", role: "ATTACCANTI", value: 15, age: 25, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p490", name: "YEBOAH", team: "VEN", role: "ATTACCANTI", value: 15, age: 26, titolarita: 4, maxSpend: 8, valCarmy: 10, valProfeta: 10, valTattico: 3, notes: "" },
  { id: "p491", name: "ADAMS", team: "VEN", role: "ATTACCANTI", value: 14, age: 26, titolarita: 4, maxSpend: 12, valCarmy: 16, valProfeta: 12, valTattico: 9, notes: "" },
  { id: "p492", name: "BERNARDESCHI", team: "BOL", role: "ATTACCANTI", value: 14, age: 32, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 8, valCarmy: 7, valProfeta: 7, valTattico: 9, notes: "" },
  { id: "p493", name: "CAMBIAGHI", team: "BOL", role: "ATTACCANTI", value: 14, age: 26, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 2, valTattico: 1, notes: "" },
  { id: "p494", name: "CANCELLIERI", team: "LAZ", role: "ATTACCANTI", value: 14, age: 24, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 1, valCarmy: 2, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p495", name: "DIA", team: "LAZ", role: "ATTACCANTI", value: 14, age: 30, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p496", name: "GHEDJEMIS", team: "FRO", role: "ATTACCANTI", value: 14, age: 24, titolarita: 3, maxSpend: 3, valCarmy: 1, valProfeta: 7, valTattico: 2, notes: "" },
  { id: "p497", name: "NERES", team: "NAP", role: "ATTACCANTI", value: 14, age: 29, titolarita: 3, maxSpend: 7, valCarmy: 11, valProfeta: 6, valTattico: 3, notes: "" },
  { id: "p498", name: "PELLEGRINO", team: "FIO", role: "ATTACCANTI", value: 14, age: 25, titolarita: 3, maxSpend: 19, valCarmy: 18, valProfeta: 27, valTattico: 12, notes: "" },
  { id: "p499", name: "SANTOS", team: "NAP", role: "ATTACCANTI", value: 14, age: 24, titolarita: 4, maxSpend: 20, valCarmy: 26, valProfeta: 20, valTattico: 15, notes: "" },
  { id: "p500", name: "BOGA", team: "JUV", role: "ATTACCANTI", value: 13, age: 29, titolarita: 3, maxSpend: 5, valCarmy: 8, valProfeta: 3, valTattico: 3, notes: "" },
  { id: "p501", name: "GEUBBELS", team: "LEC", role: "ATTACCANTI", value: 13, age: 25, titolarita: 3, maxSpend: 6, valCarmy: 4, valProfeta: 10, valTattico: 3, notes: "" },
  { id: "p502", name: "RAIMONDO", team: "FRO", role: "ATTACCANTI", value: 13, age: 22, titolarita: 3, maxSpend: 2, valCarmy: 2, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p503", name: "ROMERO", team: "PAR", role: "ATTACCANTI", value: 13, age: 23, titolarita: 3, maxSpend: 9, valCarmy: 5, valProfeta: 15, valTattico: 6, notes: "" },
  { id: "p504", name: "NOSLIN", team: "LAZ", role: "ATTACCANTI", value: 12, age: 27, titolarita: 3, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p505", name: "ORISTANIO", team: "TOR", role: "ATTACCANTI", value: 12, age: 24, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p506", name: "PIEROTTI", team: "LEC", role: "ATTACCANTI", value: 12, age: 25, altRole: "CENTROCAMPISTI", titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p507", name: "SULEMANA K", team: "ATA", role: "ATTACCANTI", value: 12, age: 24, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p508", name: "GIMENEZ", team: "MIL", role: "ATTACCANTI", value: 11, age: 25, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p509", name: "RRAHMANI", team: "VEN", role: "ATTACCANTI", value: 11, age: 26, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p510", name: "ADDAI", team: "COM", role: "ATTACCANTI", value: 10, age: 21, altRole: "CENTROCAMPISTI", titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p511", name: "ADORANTE", team: "VEN", role: "ATTACCANTI", value: 10, age: 26, titolarita: 2, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p512", name: "GIOVANE", team: "NAP", role: "ATTACCANTI", value: 10, age: 23, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p513", name: "LUCCA", team: "NAP", role: "ATTACCANTI", value: 10, age: 26, titolarita: 2, maxSpend: 2, valCarmy: 1, valProfeta: 5, valTattico: 1, notes: "" },
  { id: "p514", name: "MALDINI", team: "CAG", role: "ATTACCANTI", value: 10, age: 25, titolarita: 4, maxSpend: 3, valCarmy: 3, valProfeta: 3, valTattico: 2, notes: "" },
  { id: "p515", name: "BORRELLI", team: "CAG", role: "ATTACCANTI", value: 9, age: 26, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p516", name: "DANY MOTA", team: "MON", role: "ATTACCANTI", value: 9, age: 28, titolarita: 4, maxSpend: 1, valCarmy: 1, valProfeta: 3, valTattico: 0, notes: "" },
  { id: "p517", name: "HAVEL", team: "GEN", role: "ATTACCANTI", value: 9, age: 23, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p518", name: "KVERNADZE", team: "FRO", role: "ATTACCANTI", value: 9, age: 23, titolarita: 4, maxSpend: 2, valCarmy: 4, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p519", name: "NJIE", team: "FIO", role: "ATTACCANTI", value: 9, age: 21, notes: "" },
  { id: "p520", name: "NZOLA", team: "FIO", role: "ATTACCANTI", value: 9, age: 30, notes: "" },
  { id: "p521", name: "OSMAJIĆ", team: "GEN", role: "ATTACCANTI", value: 9, age: 27, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p522", name: "ROBINSON", team: "MON", role: "ATTACCANTI", value: 9, age: 19, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p523", name: "BIRLIGEA", team: "FRO", role: "ATTACCANTI", value: 8, age: 26, titolarita: 2, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p524", name: "CAMARDA", team: "MIL", role: "ATTACCANTI", value: 8, age: 18, titolarita: 2, maxSpend: 2, valCarmy: 1, valProfeta: 1, valTattico: 3, notes: "" },
  { id: "p525", name: "DOMINGUEZ", team: "SAS", role: "ATTACCANTI", value: 8, age: 23, altRole: "CENTROCAMPISTI", titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p526", name: "FRIGAN", team: "PAR", role: "ATTACCANTI", value: 8, age: 23, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p527", name: "KULENOVIC", team: "TOR", role: "ATTACCANTI", value: 8, age: 27, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p528", name: "VARELA", team: "MON", role: "ATTACCANTI", value: 8, age: 21, titolarita: 3, maxSpend: 6, valCarmy: 5, valProfeta: 12, valTattico: 1, notes: "" },
  { id: "p529", name: "ALMQVIST", team: "PAR", role: "ATTACCANTI", value: 7, age: 27, altRole: "CENTROCAMPISTI", titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p530", name: "EKHATOR", team: "JUV", role: "ATTACCANTI", value: 7, age: 20, titolarita: 2, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p531", name: "GONZALEZ", team: "JUV", role: "ATTACCANTI", value: 7, age: 28, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 3, valCarmy: 1, valProfeta: 0, valTattico: 9, notes: "" },
  { id: "p532", name: "GUEYE", team: "UDI", role: "ATTACCANTI", value: 7, age: 20, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p533", name: "KUHN", team: "COM", role: "ATTACCANTI", value: 7, age: 26, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p534", name: "LANG", team: "NAP", role: "ATTACCANTI", value: 7, age: 27, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p535", name: "MUTANDWA", team: "CAG", role: "ATTACCANTI", value: 7, age: 23, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p536", name: "NGONGE", team: "MON", role: "ATTACCANTI", value: 7, age: 26, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 1, notes: "" },
  { id: "p537", name: "SOTTIL", team: "FIO", role: "ATTACCANTI", value: 7, age: 27, notes: "" },
  { id: "p538", name: "BALDE", team: "MON", role: "ATTACCANTI", value: 6, age: 31, notes: "" },
  { id: "p539", name: "CISSE", team: "MIL", role: "ATTACCANTI", value: 6, age: 20, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 5, valCarmy: 3, valProfeta: 12, valTattico: 1, notes: "" },
  { id: "p540", name: "ELPHEGE", team: "PAR", role: "ATTACCANTI", value: 6, age: 25, titolarita: 3, maxSpend: 1, valCarmy: 2, valProfeta: 1, valTattico: 1, notes: "" },
  { id: "p541", name: "N’DRI", team: "LEC", role: "ATTACCANTI", value: 6, age: 26, maxSpend: 1, notes: "" },
  { id: "p542", name: "ABOUKHLAL", team: "TOR", role: "ATTACCANTI", value: 5, age: 26, altRole: "CENTROCAMPISTI", titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p543", name: "AHMED FATAH", team: "LEC", role: "ATTACCANTI", value: 5, age: 22, titolarita: 3, maxSpend: 0, valCarmy: 0, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p544", name: "FINI", team: "FRO", role: "ATTACCANTI", value: 5, age: 20, altRole: "CENTROCAMPISTI", titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 3, notes: "" },
  { id: "p545", name: "KARLSSON", team: "BOL", role: "ATTACCANTI", value: 5, age: 28, notes: "" },
  { id: "p546", name: "LONTANI", team: "PAR", role: "ATTACCANTI", value: 5, age: 18, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p547", name: "TOURE", team: "PAR", role: "ATTACCANTI", value: 5, age: 25, titolarita: 4, maxSpend: 7, valCarmy: 6, valProfeta: 10, valTattico: 6, notes: "" },
  { id: "p548", name: "VAZ", team: "ROM", role: "ATTACCANTI", value: 5, age: 19, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p549", name: "DIALLO THIAO", team: "PAR", role: "ATTACCANTI", value: 4, age: 19, notes: "" },
  { id: "p550", name: "MENDY", team: "CAG", role: "ATTACCANTI", value: 4, age: 19, titolarita: 3, maxSpend: 1, valCarmy: 1, valProfeta: 2, valTattico: 1, notes: "" },
  { id: "p551", name: "MILIK", team: "JUV", role: "ATTACCANTI", value: 4, age: 32, titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 1, valTattico: 0, notes: "" },
  { id: "p552", name: "BAYO", team: "UDI", role: "ATTACCANTI", value: 3, age: 29, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p553", name: "AZON", team: "COM", role: "ATTACCANTI", value: 2, age: 24, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p554", name: "LISMAN", team: "VEN", role: "ATTACCANTI", value: 2, age: 20, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p555", name: "PIERINI", team: "SAS", role: "ATTACCANTI", value: 2, age: 28, notes: "" },
  { id: "p556", name: "SKJELLERUP", team: "SAS", role: "ATTACCANTI", value: 2, age: 24, notes: "" },
  { id: "p557", name: "DE MARTIS DE LA .", team: "PAR", role: "ATTACCANTI", value: 1, age: 18, titolarita: 1, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p558", name: "LAERKE", team: "LEC", role: "ATTACCANTI", value: 1, age: 19, altRole: "CENTROCAMPISTI", titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p559", name: "LAUBERBACH", team: "VEN", role: "ATTACCANTI", value: 1, age: 28, titolarita: 2, maxSpend: 0, valCarmy: 1, valProfeta: 0, valTattico: 0, notes: "" },
  { id: "p560", name: "TREPY", team: "CAG", role: "ATTACCANTI", value: 1, age: 20, titolarita: 1, maxSpend: 1, valCarmy: 1, valProfeta: 0, valTattico: 2, notes: "" },
  { id: "p561", name: "VINCIATI", team: "UDI", role: "ATTACCANTI", value: 1, age: 19, notes: "" },
  { id: "p562", name: "PEJICIC", team: "UDI", role: "ATTACCANTI", value: 0, age: 19, notes: "" },
  { id: "p564", name: "BOBCEK", team: "FRO", role: "ATTACCANTI", value: 12, age: 25, titolarita: 3, maxSpend: 1, valCarmy: 0, valProfeta: 0, valTattico: 3, notes: "" },
];
